import type { Dispatch } from './data/content'
import type { SiteLinks } from './lib/posts'
import Link from 'next/link'
import Image from 'next/image'
import { ArrowRight, BriefcaseBusiness, Layers3, MapPin, Monitor, BrainCircuit, ChartNoAxesColumnIncreasing } from 'lucide-react'
import { GithubIcon, InstagramIcon, LinkedinIcon, XIcon } from './components/icons/Icons'
import penAdvert from './assets/penadvert.png'

const A=()=> <ArrowRight aria-hidden size={14}/>
const topics=[[Layers3,'Distributed Systems','Scalability, reliability, and real-world system design.','violet'],[BrainCircuit,'AI & LLMs','LLM applications, RAG, model tooling, and AI-native products.','blue'],[ChartNoAxesColumnIncreasing,'Product & Growth','From zero to first users, distribution experiments, and what actually works.','green']] as const
const projects=[['Distribution','A collection of resources, notes and experiments around product distribution and growth.','Growth · Marketing · Playbooks','distribution'],['Movie Chat RAG','A RAG based chatbot that answers questions using only Wikipedia data about movies.','RAG · LLM · Wikipedia','rag'],['Virtual Try-On','AI powered virtual try-on for apparel brands. Upload a model and try different outfits instantly.','Computer Vision · AI · E-commerce','tryon']]
const defaults=[['What I learned about Kafka partitions','A practical guide to how Kafka partitions work, the mental models that helped me, and key takeaways.','Sep 18, 2026','SYSTEMS','servers'],['Debugging is like being a detective','How I approach debugging complex issues, the mindset, and a few techniques that actually help.','Sep 12, 2026','DEV & PRODUCTIVITY','desk'],['My thoughts on building in public','What building in public has taught me, the challenges, and why I still think it’s worth it.','Sep 5, 2026','LIFE & BUILDING','sunset']]

export default function App({latestDispatches,siteLinks}:{latestDispatches:Dispatch[];siteLinks:SiteLinks}){
 const {email:EMAIL,github:GITHUB,linkedin:LINKEDIN,instagram:INSTAGRAM,x:X}=siteLinks
 const posts=defaults.map((p,i)=>({title:latestDispatches[i]?.title||p[0],desc:p[1],date:latestDispatches[i]?.date||p[2],tag:p[3],tone:p[4],href:latestDispatches[i]?.href||'/blog'}))
 return <main>
  <nav className="nav wrap"><Link className="brand" href="/">Tushar Sharma</Link><div className="navlinks"><Link href="/blog">Blogs</Link><Link href="/projects">Projects</Link><Link href="/products">Products</Link><Link href="/about">About</Link></div><a className="button dark navcta" href={'mailto:'+EMAIL}>Contact me <A/></a></nav>
  <section className="hero wrap" id="top"><div className="herocopy"><p className="eyebrow">Software engineer &amp; builder</p><h1>Software engineer.<br/>Builder. Writer.</h1><p className="lede">I build software, study distributed systems, experiment with AI, and write about what I learn.</p><div className="actions"><Link className="button dark" href="/blog">Read my writing <A/></Link><Link className="button" href="#projects">Explore projects</Link></div><div className="facts"><p><i><BriefcaseBusiness/></i><span><b>4+ years</b>building software</span></p><p><i><MapPin/></i><span><b>Based in</b>Indore, India</span></p><p><i><Monitor/></i><span><b>Open to</b>interesting opportunities</span></p></div></div><div className="portrait" id="about"><img src="/pfp.png" alt="Tushar Sharma"/><div><b>Tushar Sharma</b><span>Programmer | Building in Public | AI · Systems · Startups</span></div></div></section>
  <section className="section wrap" id="writing"><header><h2>Latest writing</h2><Link href="/blog">View all writing <A/></Link></header><div className="writing">{posts.map((p,i)=><Link className="article" href={p.href||'/blog'} key={p.title}><div className={'thumb '+p.tone}>{i===0?'01':i===1?'⌘':'☼'}</div><div className="articlecopy"><small>{p.tag}</small><h3>{p.title}</h3><p>{p.desc}</p><time>{p.date} · {8-i*2} min read</time></div></Link>)}</div></section>
  <section className="product wide" id="now"><div className="productcopy"><p className="eyebrow">Currently building</p><div className="pentitle"><div className="penlogo">▶</div><div><h2>Pen</h2><p>AI-native content and marketing OS</p></div></div><p className="productdesc">A unified workspace to plan, create, and publish content using natural language. Built for founders, creators and small teams who want to ship without the chaos.</p><div className="actions"><a className="button dark" href={'mailto:'+EMAIL+'?subject=Pen demo'}>Check out Pen <A/></a><a className="button" href={'mailto:'+EMAIL+'?subject=Pen waitlist'}>Join waitlist</a></div></div><div className="pen-advert"><Image src={penAdvert} alt="Pen AI-native content and marketing workspace" sizes="(max-width: 620px) calc(100vw - 32px), 440px" priority /></div></section>
  <section className="section wrap"><header><h2>Currently exploring</h2><Link href="/blog">Always learning <A/></Link></header><div className="topics">{topics.map(([TopicIcon,title,description,tone])=><Link href="/blog" key={title}><i className={tone}><TopicIcon/></i><span><b>{title}</b><small>{description}</small></span><A/></Link>)}</div></section>
  <section className="section wrap" id="projects"><header><h2>Selected projects</h2><a href={GITHUB} target="_blank" rel="noreferrer">View all projects <A/></a></header><div className="projects">{projects.map(p=><article className={'project '+p[3]} key={p[0]}><h3>{p[0]}</h3><p>{p[1]}</p><small>{p[2]}</small><a href={GITHUB} target="_blank" rel="noreferrer" aria-label={'View '+p[0]+' on GitHub'}>→</a></article>)}</div></section>
  <footer><div className="wrap foot"><div><b>Tushar Sharma</b><h2>Build. Learn. Share.</h2><p>Software engineer, builder and writer. Documenting the journey.</p></div><div className="social">{X&&<a href={X} target="_blank" rel="noreferrer" aria-label="X / Twitter"><XIcon/></a>}<a href={LINKEDIN} target="_blank" rel="noreferrer" aria-label="LinkedIn"><LinkedinIcon/></a><a href={GITHUB} target="_blank" rel="noreferrer" aria-label="GitHub"><GithubIcon/></a><a href={INSTAGRAM} target="_blank" rel="noreferrer" aria-label="Instagram"><InstagramIcon/></a><a className="button" href={'mailto:'+EMAIL}>Get in touch <A/></a></div></div></footer>
 </main>
}
